-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 11:20:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Datos_Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Datos_Persona` (
  `idDatos_persona` INT NOT NULL,
  `Grado_Academico` VARCHAR(45) NULL,
  `Apellido_P` VARCHAR(45) NULL,
  `Apellido_M` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Fecha_Nacimiento` VARCHAR(45) NULL,
  `Estatus` VARCHAR(45) NULL,
  `Foto` VARCHAR(45) NULL,
  PRIMARY KEY (`idDatos_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrera` (
  `idCarrera` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Abreviatura` VARCHAR(45) NULL,
  `Nivel` VARCHAR(45) NULL,
  `Estatus` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Periodo` (
  `idPeriodo` INT NOT NULL,
  `Fecha_Inicio` VARCHAR(45) NULL,
  `Fecha_Final` VARCHAR(45) NULL,
  `Estatus` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupos` (
  `idGrupos` INT NOT NULL,
  `Estatus` VARCHAR(45) NULL,
  `Grado` VARCHAR(45) NULL,
  `Grupo` VARCHAR(45) NULL,
  `Modalidad` VARCHAR(45) NULL,
  `IdCarrera` INT NULL,
  `IdPeriodo` INT NULL,
  PRIMARY KEY (`idGrupos`),
  INDEX `IdCarrera_idx` (`IdCarrera` ASC) VISIBLE,
  INDEX `idPeriodo_idx` (`IdPeriodo` ASC) VISIBLE,
  CONSTRAINT `IdCarrera`
    FOREIGN KEY (`IdCarrera`)
    REFERENCES `mydb`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPeriodo`
    FOREIGN KEY (`IdPeriodo`)
    REFERENCES `mydb`.`Periodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumnos` (
  `idAlumnos` INT NOT NULL,
  `Matricula` VARCHAR(45) NULL,
  `Estatus` VARCHAR(45) NULL,
  `IdGrupo` INT NULL,
  `IdDatos_Persona` INT NULL,
  PRIMARY KEY (`idAlumnos`),
  INDEX `IdGrupo_idx` (`IdGrupo` ASC) VISIBLE,
  INDEX `IdDatos_Persona_idx` (`IdDatos_Persona` ASC) VISIBLE,
  CONSTRAINT `IdGrupo`
    FOREIGN KEY (`IdGrupo`)
    REFERENCES `mydb`.`Grupos` (`idGrupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdDatos_Persona`
    FOREIGN KEY (`IdDatos_Persona`)
    REFERENCES `mydb`.`Datos_Persona` (`idDatos_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal` (
  `idPersonal` INT NOT NULL,
  `Numero_Trabajador` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Estatus` VARCHAR(45) NULL,
  `IdCarrera` INT NULL,
  `IdDatosPersona` INT NULL,
  PRIMARY KEY (`idPersonal`),
  INDEX `IdCarrera_idx` (`IdCarrera` ASC) VISIBLE,
  INDEX `IdDatosPersona_idx` (`IdDatosPersona` ASC) VISIBLE,
  CONSTRAINT `IdCarrera`
    FOREIGN KEY (`IdCarrera`)
    REFERENCES `mydb`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdDatosPersona`
    FOREIGN KEY (`IdDatosPersona`)
    REFERENCES `mydb`.`Datos_Persona` (`idDatos_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Laboratorio` (
  `idLaboratorio` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  `Cantidad` VARCHAR(45) NULL,
  `IdPersonal` INT NULL,
  PRIMARY KEY (`idLaboratorio`),
  INDEX `idPersonal_idx` (`IdPersonal` ASC) VISIBLE,
  CONSTRAINT `idPersonal`
    FOREIGN KEY (`IdPersonal`)
    REFERENCES `mydb`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clases` (
  `idClases` INT NOT NULL,
  `Dia` VARCHAR(45) NULL,
  `Hora_Inicio` VARCHAR(45) NULL,
  `Hora_Final` VARCHAR(45) NULL,
  `Actividad` VARCHAR(45) NULL,
  `Materia` VARCHAR(45) NULL,
  `Estatus` VARCHAR(45) NULL,
  `IdPeriodo` INT NULL,
  `IdLaboratorio` INT NULL,
  `IdPersonal` INT NULL,
  `IdGrupo` INT NULL,
  PRIMARY KEY (`idClases`),
  INDEX `idPeriodo_idx` (`IdPeriodo` ASC) VISIBLE,
  INDEX `IdPersonal_idx` (`IdPersonal` ASC) VISIBLE,
  INDEX `IdGrupo_idx` (`IdGrupo` ASC) VISIBLE,
  INDEX `idLaboratorio_idx` (`IdLaboratorio` ASC) VISIBLE,
  CONSTRAINT `idPeriodo`
    FOREIGN KEY (`IdPeriodo`)
    REFERENCES `mydb`.`Periodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdPersonal`
    FOREIGN KEY (`IdPersonal`)
    REFERENCES `mydb`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdGrupo`
    FOREIGN KEY (`IdGrupo`)
    REFERENCES `mydb`.`Grupos` (`idGrupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLaboratorio`
    FOREIGN KEY (`IdLaboratorio`)
    REFERENCES `mydb`.`Laboratorio` (`idLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recursos_Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recursos_Laboratorio` (
  `idRecursos_Laboratorio` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `No_Serie` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `IdLaboratorio` INT NULL,
  PRIMARY KEY (`idRecursos_Laboratorio`),
  INDEX `IdLaboratorio_idx` (`IdLaboratorio` ASC) VISIBLE,
  CONSTRAINT `IdLaboratorio`
    FOREIGN KEY (`IdLaboratorio`)
    REFERENCES `mydb`.`Laboratorio` (`idLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bitacora` (
  `idBitacora` INT NOT NULL,
  `IdAlumno` INT NULL,
  `IdRecursoLaboratorio` INT NULL,
  `Fecha_Entrada` VARCHAR(45) NULL,
  `Fecha_Salida` VARCHAR(45) NULL,
  `IdClase` INT NULL,
  PRIMARY KEY (`idBitacora`),
  INDEX `idAlumno_idx` (`IdAlumno` ASC) VISIBLE,
  INDEX `idRecursosLaboratorio_idx` (`IdRecursoLaboratorio` ASC) VISIBLE,
  INDEX `IdClase_idx` (`IdClase` ASC) VISIBLE,
  CONSTRAINT `idAlumno`
    FOREIGN KEY (`IdAlumno`)
    REFERENCES `mydb`.`Alumnos` (`idAlumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRecursosLaboratorio`
    FOREIGN KEY (`IdRecursoLaboratorio`)
    REFERENCES `mydb`.`Recursos_Laboratorio` (`idRecursos_Laboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdClase`
    FOREIGN KEY (`IdClase`)
    REFERENCES `mydb`.`Clases` (`idClases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
